### ISSUE TITLE
integration with pdf-tools?

### ISSUE THREAD

**Issue by gvoysey** [protesilaos/dired-preview#17]
hi prot, 

perhaps this is an obvious question, but how would i go about opening pdf-tools in a dired-preview managed window when i navigate to a pdf file?

**Comment by protesilaos** [comment]
> From: Graham Voysey ***@***.***>
> Date: Tue,  5 Nov 2024 06:45:49 -0800
>
> hi prot, 

Hello there!

> perhaps this is an obvious question, but how would i go about opening
> pdf-tools in a dired-preview managed window when i navigate to a pdf
> file?

You mean how to produce a preview or how to open the actual file? In the
former case, this should happen already but do let me know if it does
not. In the latter case, RET in dired should visit the file at point.
Otherwise, try the command 'dired-preview-find-file', which is bound to
'C-c C-f' in the 'dired-preview-mode-map'.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by rdiaz02** [comment]
What is the value of `dired-preview-ignored-extensions-regexp`  for you?  I just noticed that the default  seems to include pdf and that would explain the behavior you are seeing. If you use the value here, https://protesilaos.com/emacs/dired-preview#h:088fc7b3-7d7b-434b-80b1-e2ad20bdb4ea , that does not include pdf, it should work. In fact, the following, after doing `emacs -Q`,  works for me:

```
(package-initialize)
(dired-preview-global-mode 1)
(setq dired-preview-ignored-extensions-regexp
		  (concat "\\."
			  "\\(gz\\|"
			  "zst\\|"
			  "tar\\|"
			  "xz\\|"
			  "rar\\|"
			  "zip\\|"
			  "iso\\|"
			  "epub"
			  "\\)"))
(use-package pdf-tools
   :init (pdf-loader-install)
  :mode (("\\.pdf\\'" . pdf-view-mode)))

```


(I am using `pdf-loader-install`  instead of  `pdf-tools-install`  for slightly faster startup time).

**Comment by gvoysey** [comment]
that was it!
